name: Build iOS (Debug)

on:
  push:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  build_ios:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install Dependencies
        run: npm install

      - name: Build Web Project
        run: npm run build # Garanta que este comando gera a pasta definida no capacitor.config.ts

      - name: Capacitor Sync
        run: |
          npm install @capacitor/ios
          npx cap add ios
          npx cap sync ios

      - name: Xcode Build (Debug Simulator/Testing)
        run: |
          xcodebuild -project ios/App/App.xcodeproj \
                     -scheme App \
                     -configuration Debug \
                     -sdk iphonesimulator \
                     clean build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-debug-app
          path: ~/Library/Developer/Xcode/DerivedData/**/Build/Products/Debug-iphonesimulator/*.app
